most numpy tutorial

In [2]:
import numpy as np
# create array 3x3 array with va;ues from 0 to 8
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Display the shape, number of dimensions, size, data type, and type of the array
a.shape , a.ndim , a.size , a.dtype , type(a)

((3, 3), 2, 9, dtype('int32'), numpy.ndarray)

In [7]:
# Reshape array into a column vector (Nx1)
a.reshape((-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [8]:
# Reshape array into a column vector (1xN)
a.reshape((1,-1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [10]:
# Create a 3x4 array filled with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Create a 1D array of length 5 filled with ones
np.ones((5))

array([1., 1., 1., 1., 1.])

In [14]:
# Generate 5 evenly spaced values between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Basic array oprations
x = np.array([1,2,4,6])
# Add 10 to each element in the array
print (x + 10)
# Square each element in the array
print (x ** 2)
# Calculate the sum of the squares of the elements
print (np.sum(x ** 2))
# Get the maximum value, mean, and standard deviation of the array
np.max(x), np.mean(x), np.std(x)

[11 12 14 16]
[ 1  4 16 36]
57


(6, 3.25, 1.920286436967152)

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Slice the array to get elements from index 2 to 5
x[2:6]

array([2, 3, 4, 5])

In [28]:
# Get the last element of the array
x[-1]

9

In [33]:
# Stack arrays vertically and horizontally
a = np.array([4. , 2.])
b = np.array([3. , 8.])

# Stack array vertically (row-wise)
np.vstack([a,b])

array([[4., 2.],
       [3., 8.]])

In [34]:
# Stack array horizontally (column-wise)
np.hstack([a,b])

array([4., 2., 3., 8.])

In [36]:
# Concatenate arrays into a single array
np.concatenate([a,b])

array([4., 2., 3., 8.])

In [40]:
# Demonstrate that changing `y` also changes `x` because `y` is just a reference to `x`
x = np.arange(10)
y = x
y[0] = 100
x  # x also changes because y and x reference the same object

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [42]:
# Create a copy of `x` and modify `y` without affecting `x`
x = np.arange(10)
y = x.copy()
y[0] = 100
x  # x remains unchanged

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Perform dot product between two 1D arrays
x = np.array([1,2,3])
y = np.array([3,2,10])
x.dot(y)

37

In [45]:
# Broadcasting
a = np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
b = np.array([1,2,3])
# Add 1D array `b` to each row of the 2D array `a`
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [49]:
np.ones(4) + np.ones(4)

array([2., 2., 2., 2.])

In [54]:
np.ones((5,1)) + np.ones(3)
# Broadcasting mistakes can be tricky. Probably you didn't mean that

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [55]:
# Transpose the 2D array (swap rows and columns)
a.T

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [56]:
a = np.array([[1,2],
              [2,3]])
b = np.array([[4,1],
              [2,2]])
# Matrix multiplication using np.matmul
np.matmul(a,b)

array([[ 8,  5],
       [14,  8]])

In [58]:
# Matrix multiplication using the `@` operator (same as np.matmul)
res = a @ b
res

array([[ 8,  5],
       [14,  8]])

In [60]:
# Calculate the inverse of a matrix
from numpy.linalg import inv
inv(res)

array([[-1.33333333,  0.83333333],
       [ 2.33333333, -1.33333333]])

In [62]:
# Convert the inverse matrix to integer type
inv(res).astype(np.int64)

array([[-1,  0],
       [ 2, -1]], dtype=int64)